#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

$apiPath = __DIR__.'/../docs/api';
$templatesPath = $apiPath.'/_templates';
$destinationPath = $apiPath;

$xml = simplexml_load_file($apiPath.'/structure.xml');

$loader = new Twig_Loader_Filesystem($templatesPath);
$twig = new Twig_Environment($loader);

foreach ($xml->file as $file) {
    if (sizeof($file->class) !== 1 || (string)$file->class['namespace'] !== 'Folklore\Image') {
        continue;
    }

    $filename = snake_case((string)$file->class->name, '-').'.md';
    $destination = $destinationPath.'/'.$filename;
    $templateFilename = $filename.'.twig';
    $templatePath = file_exists($templatesPath.'/'.$templateFilename) ? $templateFilename : 'class.md.twig';
    $content = $twig->render($templatePath, [
        'file' => $file,
        'class' => $file->class,
    ]);

    file_put_contents($destination, $content);
}
